agentsofglory:
  - RayEnv:
      envname: RayEnv
      env:
        seed: 450
        n_envs: 1  # Updated to ensure n_steps * n_envs is a multiple of batch_size
      framestack:
        n_stack: 4
      agent:
        seed: 1450
        learning_rate: 0.0007
        n_steps: 64  # Ensure n_steps * n_envs is a multiple of batch_size
        batch_size: 64  # Updated to be a multiple of n_steps * n_envs
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
      learn:
        log_interval: 50
